spring:
  config:
    import:
      - classpath:/config/env.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource.url}
    username: codejuzi
    password: 12345678
  redis:
    port: 6379
    host: ${redis.host}
    password: ${redis.password}
    database: 0
  rabbitmq:
    host: ${rabbitmq.host}
    port: 5672
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl