spring:
  config:
    import:
      - classpath:/database_config/database.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  redis:
    port: 6379
    host: ${redis.host}
    database: 0
#    username: ${redis.username}
#    password: ${redis.password}
  rabbitmq:
    host: ${rabbitmq.host}
    port: 5672
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}