spring:
  config:
    import:
      - classpath:/database_config/database.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource.url}
    username: codejuzi
    password: 12345678
  redis:
    port: 6379
    host: ${redis.dev.host}
    database: 0
  rabbitmq:
    host: ${rabbitmq.dev.host}
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl