spring:
  application:
    name: oj-backend
  profiles:
    active: dev
  session:
    # 失效时间：1天
    timeout: 86400
    store-type: localhost
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/*.xml
  type-aliases-package: com.juzi.oj.model.entity
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: not_null
      where-strategy: not_null

codesandbox:
  type: example